name: lint-and-format

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install Dependencies
        run: |
          poetry install --only dev

      - name: Format with isort and black
        run: |
          poetry run isort --check-only --diff ./
          poetry run black --check --diff ./

      - name: Lint with RUFF
        run: |
          poetry run ruff ./
